# Cleaned Nasdaq Data 
#### Data Wrangling Project | Matt Lancaster, Advika Shah | 5/3/25

In [1]:
# import required packages
import pandas as pd
import numpy as np

In [2]:
# load the two separate datasets
# nasdaq_final.csv
nasdaq_final = pd.read_csv('nasdaq_final.csv', encoding = 'utf-8')

# fin_stmts.csv
fin_stmts = pd.read_csv('fin_stmts.csv', encoding = 'utf-8')

# drop 'Unnamed:0' columns
nasdaq_final = nasdaq_final.drop(columns = 'Unnamed: 0')
fin_stmts = fin_stmts.drop(columns = 'Unnamed: 0')

display(nasdaq_final)
display(fin_stmts)

,Ticker,Name,Last Sale,Net Change,Percent Change,Market Cap
0,MSFT,Microsoft Corporation Common Stock,$425.40,30.14,7.625%,"3,162,416,042,769"
1,NVDA,NVIDIA Corporation Common Stock,$111.61,2.69,2.47%,"2,723,284,000,000"
2,AMZN,"Amazon.com, Inc. Common Stock",$190.20,5.78,3.134%,"2,015,688,122,750"
3,GOOG,Alphabet Inc. Class C Capital Stock,$162.79,1.90,1.181%,"1,975,456,650,000"
4,GOOGL,Alphabet Inc. Class A Common Stock,$161.30,2.50,1.574%,"1,957,375,500,000"
...,...,...,...,...,...,...
6556,XFLT-A,XAI Octagon Floating Rate & Alternative Income...,$25.17,0.01,0.04%,NaN
6557,YCBD-A,"cbdMD, Inc. 8.0% Series A Cumulative Convertib...",$1.67,0.12,7.742%,NaN
6558,YHNA,YHN Acquisition I Limited Ordinary Shares,$10.24,UNCH,--,NaN
6559,YHNAR,YHN Acquisition I Limited Right,$0.1329,-0.0071,-5.071%,NaN
6560,ZTR,Virtus Total Return Fund Inc.,$6.07,0.06,0.998%,NaN

,Ticker,Share Issued,Total Assets,Net PPE,Accounts Receivable,Cash And Cash Equivalents,Total Debt,Accounts Payable,Stockholders Equity,Retained Earnings,Working Capital,Total Revenue,Operating Income,EBITDA,Net Income,Capital Expenditure,Free Cash Flow
0,AX,7.081364e+07,2.398115e+10,NaN,3.009070e+08,2.001321e+09,4.374270e+08,3.143990e+08,2.603900e+09,2.507850e+09,NaN,3.046600e+08,NaN,NaN,1.052060e+08,-8551000.0,6.513000e+07
1,MRUS,6.882875e+07,7.826930e+08,2.002400e+07,1.261000e+06,2.932940e+08,9.912000e+06,4.164000e+06,6.479270e+08,-9.683870e+08,4.819960e+08,9.140000e+06,-8.865200e+07,-8.806300e+07,-3.092300e+07,-20000.0,-6.667800e+07
2,TENX,2.982810e+05,9.668600e+07,NaN,NaN,9.485100e+07,NaN,3.157000e+06,9.199300e+07,-3.148550e+08,9.199300e+07,0.000000e+00,-7.294772e+06,-6.267483e+06,-6.267018e+06,NaN,-3.527033e+06
3,RYTM,6.239065e+07,3.922730e+08,4.109000e+06,1.851200e+07,8.913700e+07,3.938000e+06,1.232800e+07,1.645490e+08,-1.155338e+09,2.586830e+08,4.183000e+07,-4.125500e+07,-3.755200e+07,-4.329200e+07,NaN,-1.884500e+07
4,GALT,6.230808e+07,1.749500e+07,0.000000e+00,NaN,1.512000e+07,1.062450e+08,5.656000e+06,-1.030700e+08,-4.015720e+08,-1.815700e+07,0.000000e+00,-1.242800e+07,-1.023200e+07,-1.196700e+07,NaN,-1.279100e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,DXCM,4.103000e+08,6.751700e+09,1.423800e+09,1.155200e+09,9.049000e+08,2.583200e+09,4.320000e+08,2.266600e+09,1.703000e+09,1.516700e+09,1.036000e+09,1.337000e+08,2.190000e+08,1.054000e+08,-87000000.0,9.680000e+07
566,MCD,1.660600e+09,5.518200e+10,3.863400e+10,2.383000e+09,1.085000e+09,5.194800e+10,1.029000e+09,-3.796000e+09,6.683400e+10,7.380000e+08,6.388000e+09,2.879000e+09,3.471000e+09,2.016000e+09,-807000000.0,1.824000e+09
567,SVII,9.880096e+06,2.611080e+07,NaN,NaN,4.953520e+05,1.500000e+06,8.876800e+04,2.440203e+07,-1.152822e+06,-1.152055e+06,0.000000e+00,-2.260100e+05,-2.260100e+05,9.451360e+05,NaN,-2.323610e+05
568,CERT,1.619588e+08,1.575104e+09,1.600800e+07,9.060900e+07,1.791830e+08,3.118970e+08,3.502000e+06,1.058656e+09,-1.282810e+08,1.647640e+08,1.003610e+08,6.003000e+06,2.540000e+07,6.577000e+06,-5836000.0,4.353300e+07
569,GGR,2.950665e+08,7.004270e+08,4.735580e+08,1.697700e+07,1.171480e+08,3.931800e+08,2.927100e+07,1.765400e+08,-5.487320e+08,-2.280500e+07,7.313000e+07,-2.386800e+07,-4.180500e+07,-7.132800e+07,-60510000.0,-6.392200e+07

In [3]:
# merge nasdaq_final and fin_stmts
final_df = pd.merge(nasdaq_final, fin_stmts, how = 'inner', on = 'Ticker')
display(final_df)

,Ticker,Name,Last Sale,Net Change,Percent Change,Market Cap,Share Issued,Total Assets,Net PPE,Accounts Receivable,...,Accounts Payable,Stockholders Equity,Retained Earnings,Working Capital,Total Revenue,Operating Income,EBITDA,Net Income,Capital Expenditure,Free Cash Flow
0,AVGO,Broadcom Inc. Common Stock,$197.33,4.86,2.525%,"927,835,540,326",4.702000e+09,1.653580e+11,2.465000e+09,4.955000e+09,...,1.905000e+09,6.978900e+10,2.729000e+09,8.000000e+07,1.491600e+10,6.432000e+09,8.537000e+09,5.503000e+09,-1.000000e+08,6.013000e+09
1,V,Visa Inc.,$342.45,-3.05,-0.883%,"636,195,842,892",1.920649e+09,9.285300e+10,4.023000e+09,2.719000e+09,...,4.210000e+08,3.803000e+10,1.651800e+10,2.553000e+09,9.594000e+09,6.435000e+09,5.901000e+09,4.577000e+09,-3.270000e+08,4.368000e+09
2,XOM,Exxon Mobil Corporation Common Stock,$105.78,0.15,0.142%,"458,994,579,649",8.019095e+09,4.534750e+11,2.943180e+11,3.528200e+10,...,3.614500e+10,2.637050e+11,4.709030e+11,2.168300e+10,8.105800e+10,7.773000e+09,1.669500e+10,7.610000e+09,-6.837000e+09,5.392000e+09
3,HD,"Home Depot, Inc. (The) Common Stock",$358.30,-2.19,-0.608%,"356,161,725,794",1.800000e+09,9.611900e+10,3.529400e+10,4.319000e+09,...,1.193800e+10,6.640000e+09,8.953300e+10,3.022000e+09,3.970400e+10,4.495000e+09,5.534000e+09,2.997000e+09,-1.101000e+09,3.570000e+09
4,PLTR,Palantir Technologies Inc. Class A Common Stock,$116.20,-2.24,-1.891%,"272,530,425,997",2.338795e+09,6.340884e+09,2.403780e+08,5.750480e+08,...,1.030000e+05,5.003275e+09,-5.187423e+09,4.938271e+09,8.275190e+08,1.104300e+07,1.804900e+07,7.900900e+07,-3.106000e+06,4.572210e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,HLXB,Helix Acquisition Corp. II Class A Ordinary Sh...,$10.85,-0.05,-0.459%,NaN,2.350900e+07,1.944242e+08,NaN,NaN,...,NaN,1.887167e+08,-3.733121e+06,1.762262e+06,0.000000e+00,-2.958930e+05,-2.958930e+05,1.953176e+06,NaN,-8.785900e+04
566,HSPO,Horizon Space Acquisition I Corp. Ordinary Shares,$11.79,UNCH,--,NaN,7.832390e+06,2.132791e+07,NaN,NaN,...,NaN,1.693109e+07,-4.389235e+06,-1.974004e+06,0.000000e+00,-2.571800e+05,-2.571800e+05,4.532840e+05,NaN,-3.203540e+05
567,KFII,K&F Growth Acquisition Corp. II Class A Ordina...,$10.03,UNCH,--,NaN,3.416231e+07,1.428380e+05,NaN,NaN,...,NaN,-2.017300e+04,-4.517300e+04,-1.536290e+05,0.000000e+00,-1.804000e+04,-1.804000e+04,-1.804000e+04,NaN,0.000000e+00
568,NETD,Nabors Energy Transition Corp. II Class A Ordi...,$11.01,0.01,0.091%,NaN,3.812500e+07,3.335163e+08,NaN,NaN,...,2.963680e+05,3.157183e+08,-1.606358e+07,1.421438e+06,0.000000e+00,-3.156494e+06,-3.156494e+06,6.112450e+05,NaN,-4.541200e+04
569,SVII,Spring Valley Acquisition Corp. II Class A Ord...,$11.67,UNCH,--,NaN,9.880096e+06,2.611080e+07,NaN,NaN,...,8.876800e+04,2.440203e+07,-1.152822e+06,-1.152055e+06,0.000000e+00,-2.260100e+05,-2.260100e+05,9.451360e+05,NaN,-2.323610e+05

In [4]:
# reformat the columns' data types for analysis
import numpy as np

final_df['Last Sale'] = final_df['Last Sale'].str.replace('$', '', regex = False)
final_df['Last Sale'] = final_df['Last Sale'].replace(',', '',regex = True).astype(float)

final_df['Percent Change'] = final_df['Percent Change'].str.replace('%', '', regex = False)
final_df['Percent Change'] = final_df['Percent Change'].str.replace('--', '0', regex = False).astype(float)

final_df['Net Change'] = final_df['Net Change'].str.replace('UNCH', '0', regex = False).astype(float)

final_df['Market Cap'] = final_df['Market Cap'].str.replace(',', '', regex = True)
final_df['Market Cap'] = final_df['Market Cap'].replace('NA', np.nan)
final_df['Market Cap'] = final_df['Market Cap'].astype(float)
 
final_df['Share Issued'] = final_df['Share Issued'].astype(float)
final_df['Total Assets'] = final_df['Total Assets'].astype(float) 
final_df['Net PPE'] = final_df['Net PPE'].astype(float) 
final_df['Accounts Receivable'] = final_df['Accounts Receivable'].astype(float) 
final_df['Cash And Cash Equivalents'] = final_df['Cash And Cash Equivalents'].astype(float) 
final_df['Total Debt'] = final_df['Total Debt'].astype(float) 
final_df['Accounts Payable'] = final_df['Accounts Payable'].astype(float) 
final_df['Stockholders Equity'] = final_df['Stockholders Equity'].astype(float) 
final_df['Retained Earnings'] = final_df['Retained Earnings'].astype(float) 
final_df['Working Capital'] = final_df['Working Capital'].astype(float) 
final_df['Total Revenue'] = final_df['Total Revenue'].astype(float) 
final_df['Operating Income'] = final_df['Operating Income'].astype(float)
final_df['EBITDA'] = final_df['EBITDA'].astype(float) 
final_df['Net Income'] = final_df['Net Income'].astype(float) 
final_df['Capital Expenditure'] = final_df['Capital Expenditure'].astype(float) 
final_df['Free Cash Flow'] = final_df['Free Cash Flow'].astype(float) 

# change the df settings to not display values in a scientific notation format
pd.options.display.float_format = '{:.2f}'.format

display(final_df)

,Ticker,Name,Last Sale,Net Change,Percent Change,Market Cap,Share Issued,Total Assets,Net PPE,Accounts Receivable,...,Accounts Payable,Stockholders Equity,Retained Earnings,Working Capital,Total Revenue,Operating Income,EBITDA,Net Income,Capital Expenditure,Free Cash Flow
0,AVGO,Broadcom Inc. Common Stock,197.33,4.86,2.52,927835540326.00,4702000000.00,165358000000.00,2465000000.00,4955000000.00,...,1905000000.00,69789000000.00,2729000000.00,80000000.00,14916000000.00,6432000000.00,8537000000.00,5503000000.00,-100000000.00,6013000000.00
1,V,Visa Inc.,342.45,-3.05,-0.88,636195842892.00,1920648651.00,92853000000.00,4023000000.00,2719000000.00,...,421000000.00,38030000000.00,16518000000.00,2553000000.00,9594000000.00,6435000000.00,5901000000.00,4577000000.00,-327000000.00,4368000000.00
2,XOM,Exxon Mobil Corporation Common Stock,105.78,0.15,0.14,458994579649.00,8019094536.00,453475000000.00,294318000000.00,35282000000.00,...,36145000000.00,263705000000.00,470903000000.00,21683000000.00,81058000000.00,7773000000.00,16695000000.00,7610000000.00,-6837000000.00,5392000000.00
3,HD,"Home Depot, Inc. (The) Common Stock",358.30,-2.19,-0.61,356161725794.00,1800000000.00,96119000000.00,35294000000.00,4319000000.00,...,11938000000.00,6640000000.00,89533000000.00,3022000000.00,39704000000.00,4495000000.00,5534000000.00,2997000000.00,-1101000000.00,3570000000.00
4,PLTR,Palantir Technologies Inc. Class A Common Stock,116.20,-2.24,-1.89,272530425997.00,2338795190.00,6340884000.00,240378000.00,575048000.00,...,103000.00,5003275000.00,-5187423000.00,4938271000.00,827519000.00,11043000.00,18049000.00,79009000.00,-3106000.00,457221000.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
565,HLXB,Helix Acquisition Corp. II Class A Ordinary Sh...,10.85,-0.05,-0.46,NaN,23509000.00,194424196.00,NaN,NaN,...,NaN,188716681.00,-3733121.00,1762262.00,0.00,-295893.00,-295893.00,1953176.00,NaN,-87859.00
566,HSPO,Horizon Space Acquisition I Corp. Ordinary Shares,11.79,0.00,0.00,NaN,7832390.00,21327906.00,NaN,NaN,...,NaN,16931087.00,-4389235.00,-1974004.00,0.00,-257180.00,-257180.00,453284.00,NaN,-320354.00
567,KFII,K&F Growth Acquisition Corp. II Class A Ordina...,10.03,0.00,0.00,NaN,34162310.00,142838.00,NaN,NaN,...,NaN,-20173.00,-45173.00,-153629.00,0.00,-18040.00,-18040.00,-18040.00,NaN,0.00
568,NETD,Nabors Energy Transition Corp. II Class A Ordi...,11.01,0.01,0.09,NaN,38125000.00,333516287.00,NaN,NaN,...,296368.00,315718315.00,-16063578.00,1421438.00,0.00,-3156494.00,-3156494.00,611245.00,NaN,-45412.00
569,SVII,Spring Valley Acquisition Corp. II Class A Ord...,11.67,0.00,0.00,NaN,9880096.00,26110797.00,NaN,NaN,...,88768.00,24402029.00,-1152822.00,-1152055.00,0.00,-226010.00,-226010.00,945136.00,NaN,-232361.00

In [5]:
final_df.dtypes

Ticker                        object
Name                          object
Last Sale                    float64
Net Change                   float64
Percent Change               float64
Market Cap                   float64
Share Issued                 float64
Total Assets                 float64
Net PPE                      float64
Accounts Receivable          float64
Cash And Cash Equivalents    float64
Total Debt                   float64
Accounts Payable             float64
Stockholders Equity          float64
Retained Earnings            float64
Working Capital              float64
Total Revenue                float64
Operating Income             float64
EBITDA                       float64
Net Income                   float64
Capital Expenditure          float64
Free Cash Flow               float64
dtype: object

In [6]:
# save final_df as a csv
final_df.to_csv('final_data.csv', encoding = 'utf-8')