# Financial Statement Data

#### Data Wrangling Project | Matt Lancaster, Advika Shah | 5/3/25

In [6]:
# import required packages
import pandas as pd
import yfinance as yf

In [4]:
# import nasdaq_final.csv
nasdaq_df = pd.read_csv('nasdaq_final.csv', encoding = 'utf-8')
display(nasdaq_df)

,Unnamed: 0,Ticker,Name,Last Sale,Net Change,Percent Change,Market Cap
0,0,MSFT,Microsoft Corporation Common Stock,$425.40,30.14,7.625%,"3,162,416,042,769"
1,1,NVDA,NVIDIA Corporation Common Stock,$111.61,2.69,2.47%,"2,723,284,000,000"
2,2,AMZN,"Amazon.com, Inc. Common Stock",$190.20,5.78,3.134%,"2,015,688,122,750"
3,3,GOOG,Alphabet Inc. Class C Capital Stock,$162.79,1.90,1.181%,"1,975,456,650,000"
4,4,GOOGL,Alphabet Inc. Class A Common Stock,$161.30,2.50,1.574%,"1,957,375,500,000"
...,...,...,...,...,...,...,...
6556,6556,XFLT-A,XAI Octagon Floating Rate & Alternative Income...,$25.17,0.01,0.04%,NaN
6557,6557,YCBD-A,"cbdMD, Inc. 8.0% Series A Cumulative Convertib...",$1.67,0.12,7.742%,NaN
6558,6558,YHNA,YHN Acquisition I Limited Ordinary Shares,$10.24,UNCH,--,NaN
6559,6559,YHNAR,YHN Acquisition I Limited Right,$0.1329,-0.0071,-5.071%,NaN
6560,6560,ZTR,Virtus Total Return Fund Inc.,$6.07,0.06,0.998%,NaN

In [5]:
# randomly select 500 stocks from the nasdaq_df to download Yahoo Finance data on
nasdaq_500 = nasdaq_df.sample(n=500, random_state = 42)
display(nasdaq_500)

,Unnamed: 0,Ticker,Name,Last Sale,Net Change,Percent Change,Market Cap
1433,1433,AX,"Axos Financial, Inc. Common Stock",$65.50,2.02,3.182%,"3,739,950,178"
1558,1558,MRUS,Merus N.V. Common Shares,$45.45,-0.06,-0.132%,"3,140,161,816"
4830,4830,TENX,"Tenax Therapeutics, Inc. Common Stock",$5.73,-0.03,-0.521%,"22,750,306"
6000,6000,EQH-A,"Equitable Holdings, Inc. Depositary Shares",$20.02,0.02,0.10%,NaN
1374,1374,RYTM,"Rhythm Pharmaceuticals, Inc. Common Stock",$63.80,-1.39,-2.132%,"4,033,673,783"
...,...,...,...,...,...,...,...
1789,1789,CWK,Cushman & Wakefield plc Ordinary Shares,$9.60,0.23,2.455%,"2,220,359,251"
4536,4536,CATO,Cato Corporation (The) Class A Common Stock,$2.33,-0.03,-1.271%,"46,780,764"
1192,1192,GPI,"Group 1 Automotive, Inc. Common Stock",$405.33,1.70,0.421%,"5,242,829,652"
4710,4710,CDROW,"Codere Online Luxembourg, S.A. Warrants",$0.7001,UNCH,--,"31,589,881"
1412,1412,NNI,"Nelnet, Inc. Common Stock",$105.71,-0.38,-0.358%,"3,836,538,633"

In [7]:
# make a list of all the ticker symbols for the 500 randomly-sampled nasdaq stocks
ticker_list = nasdaq_500['Ticker'].unique()
print(ticker_list)

['AX' 'MRUS' 'TENX' 'EQH-A' 'RYTM' 'GALT' 'ATR' 'CHRW' 'FFIC' 'GEVO' 'CVI'
 'CHA' 'INVA' 'TBCH' 'AREN' 'LUNG' 'BC-C' 'LDI' 'VATE' 'JACK' 'ECG' 'ADI'
 'FRT-C' 'NUKKW' 'CLVT' 'BTM' 'KFRC' 'RANGU' 'MTH' 'INSP' 'XTIA' 'NEHC'
 'FSBW' 'CASS' 'HOG' 'HPKEW' 'LBTYB' 'PAYC' 'GLP-B' 'VEL' 'TIVC' 'PMM'
 'PCG-I' 'AMPGW' 'ABR-D' 'IMCC' 'PHX' 'GPN' 'OCTO' 'CLFD' 'NOVT' 'FHN-E'
 'NCI' 'BBGI' 'EHTH' 'SHOP' 'MI' 'KIM-N' 'CUBA' 'OXLCZ' 'SNTI' 'NBR'
 'SCLX' 'GGROW' 'LENZ' 'OCCI' 'ICMB' 'H' 'CNTA' 'PFN' 'PSO' 'ATOM' 'RANI'
 'MBRX' 'KZR' 'AMX' 'ABCL' 'TRC' 'EHAB' 'GILT' 'UCTT' 'VYGR' 'PINC' 'PAHC'
 'PLTR' 'INVZ' 'MOVE' 'MYPS' 'PRFX' 'BPYPN' 'ZION' 'BDX' 'WTBA' 'FPF'
 'CHCT' 'SRPT' 'BKKT' 'ASB' 'AEO' 'JBHT' 'JOBY' 'VREX' 'PVH' 'HD' 'HSPO'
 'NTRA' 'CHSCP' 'GPMT-A' 'CBZ' 'NREF-A' 'COR' 'HTFB' 'REBN' 'IMAB' 'USCB'
 'RDVT' 'SUNE' 'MERC' 'AACT' 'ADAP' 'RBKB' 'FPI' 'ATXG' 'UONE' 'WINA'
 'OESX' 'MRTN' 'QSI' 'CLSK' 'CNET' 'SXTC' 'BKSY' 'EDAP' 'ARDC' 'ARKO'
 'AISP' 'ENS' 'PHOE' 'GFI' 'JMSB' 'MIDD' 'MMYT' 'AHT' 'MAN' 'GLU' 'OVBC'
 'GFS' 'PAGP' 'MWYN' 'WLK' 'XELB' 'TNFA' 'ALUR' 'TEO' 'WD' 'FTLF' 'OLLI'
 'TPTA' 'HLX' 'RWT-A' 'WTF' 'MXCT' 'MTSI' 'AMZE' 'TXN' 'BRLS' 'PSA-G'
 'AUST' 'JBL' 'SCNI' 'OTIS' 'HDSN' 'NOVA' 'SXC' 'EL' 'STI' 'TGS' 'CCRD'
 'FBIO' 'GB' 'ANGO' 'OKUR' 'DTE' 'ORMP' 'MXC' 'ORGNW' 'OCSL' 'SAT' 'MAT'
 'CVM' 'CNEY' 'PINE' 'NUWE' 'FLDDW' 'TCBI' 'SB-C' 'FTAIM' 'WNC' 'IP'
 'CHSCN' 'MNSBP' 'SLSR' 'SHO-H' 'MSIF' 'PPBT' 'GGG' 'KELYA' 'TDY' 'NSIT'
 'GAN' 'HQH' 'LOVE' 'MAG' 'SYTA' 'GGT' 'CAAP' 'BYSI' 'NEUP' 'VGZ' 'ACCO'
 'FRA' 'DOCN' 'TBN' 'RWT' 'MHK' 'IIM' 'ATCOL' 'LYEL' 'OXLCL' 'PFE' 'SB'
 'KRT' 'GDV-H' 'NU' 'BB' 'DASH' 'GIS' 'ADN' 'BCS' 'PRTC' 'DCO' 'JRVR'
 'ASB-F' 'SEED' 'SLG' 'WLDN' 'MRSN' 'DELL' 'CNM' 'SUGP' 'TRP' 'SLQT' 'DXF'
 'HURN' 'CURV' 'HNNA' 'UBFO' 'RMMZ' 'COCH' 'FGEN' 'NAVI' 'IMNN' 'LOKVW'
 'OXLCN' 'AIRTP' 'DTI' 'AMBC' 'DSGN' 'TAP' 'PW' 'PII' 'EOT' 'RL' 'OSS'
 'UNM' 'CRNT' 'KWE' 'MRT' 'CRBU' 'RVT' 'MDV' 'CLMT' 'CNQ' 'GDL' 'MMA'
 'DNLI' 'F-B' 'FRMEP' 'JQC' 'OXLCP' 'QTRX' 'NIU' 'NVAWW' 'EKSO' 'DLR-K'
 'YHC' 'TTI' 'GDC' 'FCAP' 'UFPT' 'EVTL' 'AVT' 'BTOC' 'DDOG' 'SPNT-B'
 'BFS-D' 'BPT' 'AUR' 'TALKW' 'DXLG' 'CRGOW' 'IHRT' 'AERT' 'HBB' 'OKTA'
 'XCUR' 'GAINL' 'TEN' 'LU' 'ATO' 'MYRG' 'SKT' 'WNEB' 'PKG' 'CNS' 'NETD'
 'HNRG' 'CVKD' 'KLTR' 'HLXB' 'PLMKU' 'CCZ' 'SCE-J' 'GELS' 'LFMD' 'FLUT'
 'BDMDW' 'APLS' 'MPWR' 'MGF' 'TPG' 'ONMDW' 'CSPI' 'SNX' 'SCE-N' 'CREV'
 'FLNC' 'TSN' 'HYLN' 'RVMD' 'GSRT' 'MDCX' 'AGAE' 'TOP' 'DGII' 'QVCGB' 'KB'
 'SIM' 'MEI' 'CMRE-B' 'MRX' 'SAGT' 'OMCC' 'YJ' 'ADAG' 'IMMP' 'MURA' 'FIZZ'
 'ZS' 'NNOX' 'MATW' 'KRUS' 'FHTX' 'XPRO' 'CNVS' 'CDNS' 'WEC' 'ASPI' 'TRSG'
 'POST' 'OPFI' 'SOHOB' 'IPA' 'STKS' 'BPMC' 'COOK' 'SJ' 'RBA' 'JKS' 'GBR'
 'ELMD' 'DMAC' 'SERA' 'GORO' 'FAAS' 'FT' 'THG' 'PZG' 'GREEL' 'TCMD' 'PLMR'
 'MUFG' 'BBVA' 'IBO' 'SCWO' 'BAYAR' 'IPW' 'SKYW' 'EYPT' 'MIO' 'INFY' 'HUM'
 'ALGS' 'CMRE' 'DXPE' 'BAERW' 'ARI' 'ASPCR' 'OXLCI' 'HMR' 'ELVA' 'SFL'
 'DTST' 'ITIC' 'SHEL' 'DHIL' 'WCT' 'WAFU' 'KIM-L' 'KFII' 'GLTO' 'RAVE'
 'OABI' 'KEP' 'LHX' 'UTHR' 'KOF' 'JEQ' 'GOLF' 'AGNCN' 'BASE' 'BULL' 'FTV'
 'SIMAW' 'TAC' 'EVH' 'DYNXW' 'VRE' 'ELLO' 'NGVT' 'NQP' 'EBTC' 'RDZN' 'TAL'
 'AGRI' 'PARR' 'C' 'MKSI' 'ASTI' 'PAL' 'ACCS' 'VIGL' 'IDXX' 'SPG' 'MGR'
 'KEY-L' 'IAC' 'VCIC' 'ULS' 'CIFR' 'ANTE' 'SNYR' 'FRSH' 'MFM' 'TTE' 'XBP'
 'TCOM' 'DLY' 'WU' 'VNCE' 'SGU' 'SGN' 'RAND' 'MSA' 'MEGL' 'XOM' 'YOU'
 'CXM' 'UNTY' 'RVMDW' 'MD' 'QRHC' 'CIMN' 'MUR' 'BBSI' 'CWK' 'CATO' 'GPI'
 'CDROW' 'NNI']

In [9]:
# download all the stock information for ticker_list
for ticker in ticker_list:
    stock_information = yf.download(ticker, '2024-04-26')

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['EQH-A']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BC-C']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['FRT-C']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GLP-B']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PCG-I']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABR-D']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['FHN-E']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['KIM-N']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GGROW']: YFInvalidPeriodError("GGROW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GPMT-A']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['NREF-A']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['RWT-A']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PSA-G']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ORGNW']: YFInvalidPeriodError("ORGNW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['FLDDW']: YFInvalidPeriodError("FLDDW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SB-C']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SHO-H']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['GDV-H']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ASB-F']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['LOKVW']: YFInvalidPeriodError("LOKVW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['F-B']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['NVAWW']: YFInvalidPeriodError("NVAWW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DLR-K']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SPNT-B']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BFS-D']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['TALKW']: YFInvalidPeriodError("TALKW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CRGOW']: YFInvalidPeriodError("CRGOW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SCE-J']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BDMDW']: YFInvalidPeriodError("BDMDW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ONMDW']: YFInvalidPeriodError("ONMDW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SCE-N']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CMRE-B']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BAYAR']: YFInvalidPeriodError("BAYAR: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BAERW']: YFInvalidPeriodError("BAERW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ASPCR']: YFInvalidPeriodError("ASPCR: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['KIM-L']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['SIMAW']: YFInvalidPeriodError("SIMAW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DYNXW']: YFInvalidPeriodError("DYNXW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['KEY-L']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['RVMDW']: YFInvalidPeriodError("RVMDW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['CDROW']: YFInvalidPeriodError("CDROW: Period 'max' is invalid, must be of the format 1d, 5d, etc.")
[*********************100%***********************]  1 of 1 completed

In [10]:
# balance sheet data for each ticker
balance_sheets = []
for ticker in ticker_list:
    tkr = yf.Ticker(ticker)
    balance_sheet = tkr.quarterly_balance_sheet.transpose()
    balance_sheet.insert(0, 'Ticker', tkr.ticker)
    balance_sheets.append(balance_sheet.head(1))
    
final_bs = pd.concat(balance_sheets, ignore_index = True)

display(final_bs)

,Ticker,Treasury Shares Number,Ordinary Shares Number,Share Issued,Total Debt,Tangible Book Value,Invested Capital,Net Tangible Assets,Common Stock Equity,Total Capitalization,...,Investmentsin Joint Venturesat Cost,Minimum Pension Liabilities,Unrealized Gain Loss,Total Partnership Capital,General Partnership Capital,Limited Partnership Capital,Investmentsin Subsidiariesat Cost,Current Deferred Taxes Liabilities,Current Deferred Taxes Assets,Fixed Assets Revaluation Reserve
0,AX,13948113.0,56865524.0,70813637.0,437427000.0,2440349000.0,3041327000.0,2440349000.0,2603900000.0,3041327000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MRUS,NaN,68828749.0,68828749.0,9912000.0,646248000.0,647927000.0,646248000.0,647927000.0,647927000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TENX,NaN,298281.0,298281.0,NaN,91993000.0,91993000.0,91993000.0,91993000.0,91993000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RYTM,NaN,62390654.0,62390654.0,3938000.0,15555000.0,21729000.0,158375000.0,21729000.0,164549000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GALT,NaN,62308075.0,62308075.0,106245000.0,-105293000.0,933000.0,-103070000.0,-105293000.0,-17961000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,BBSI,NaN,25784000.0,25784000.0,21446000.0,173584000.0,221404000.0,173584000.0,221404000.0,221404000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
445,CWK,NaN,231281053.0,231281053.0,3273800000.0,-926800000.0,4795400000.0,-926800000.0,1776400000.0,4686900000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
446,CATO,NaN,20537776.0,20537776.0,145896000.0,162296000.0,162296000.0,162296000.0,162296000.0,162296000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
447,GPI,11932681.0,13031697.0,24964378.0,5268200000.0,-33000000.0,7955800000.0,-33000000.0,2992400000.0,5653500000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
448,NNI,11305731.0,36293352.0,47599083.0,8309797000.0,3155405000.0,11659559000.0,3155405000.0,3349762000.0,10716394000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# only include relevant columns
final_bs = final_bs[['Ticker', 'Share Issued', 'Total Assets',
                    'Net PPE', 'Inventory', 'Accounts Receivable',
                    'Cash And Cash Equivalents', 'Total Debt', 'Long Term Debt',
                    'Current Debt', 'Accounts Payable', 'Stockholders Equity',
                    'Retained Earnings', 'Working Capital']]

display(final_bs)

,Ticker,Share Issued,Total Assets,Net PPE,Inventory,Accounts Receivable,Cash And Cash Equivalents,Total Debt,Long Term Debt,Current Debt,Accounts Payable,Stockholders Equity,Retained Earnings,Working Capital
0,AX,70813637.0,23981154000.0,NaN,NaN,300907000.0,2001321000.0,437427000.0,437427000.0,0.0,314399000.0,2603900000.0,2507850000.0,NaN
1,MRUS,68828749.0,782693000.0,20024000.0,NaN,1261000.0,293294000.0,9912000.0,NaN,NaN,4164000.0,647927000.0,-968387000.0,481996000.0
2,TENX,298281.0,96686000.0,NaN,NaN,NaN,94851000.0,NaN,NaN,NaN,3157000.0,91993000.0,-314855000.0,91993000.0
3,RYTM,62390654.0,392273000.0,4109000.0,18741000.0,18512000.0,89137000.0,3938000.0,NaN,NaN,12328000.0,164549000.0,-1155338000.0,258683000.0
4,GALT,62308075.0,17495000.0,0.0,NaN,NaN,15120000.0,106245000.0,85109000.0,21117000.0,5656000.0,-103070000.0,-401572000.0,-18157000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,BBSI,25784000.0,745508000.0,77110000.0,NaN,234533000.0,55367000.0,21446000.0,NaN,NaN,6787000.0,221404000.0,199995000.0,116546000.0
445,CWK,231281053.0,7407500000.0,405300000.0,NaN,1307200000.0,623200000.0,3273800000.0,2910500000.0,108500000.0,1095100000.0,1776400000.0,-984000000.0,401600000.0
446,CATO,20537776.0,452361000.0,209196000.0,110739000.0,11428000.0,20279000.0,145896000.0,NaN,NaN,88641000.0,162296000.0,31935000.0,34947000.0
447,GPI,24964378.0,9887000000.0,3211600000.0,2558400000.0,316700000.0,70500000.0,5268200000.0,2661100000.0,2302300000.0,727900000.0,2992400000.0,4243900000.0,4900000.0
448,NNI,47599083.0,13777753000.0,95185000.0,NaN,159934000.0,194518000.0,8309797000.0,7366632000.0,943165000.0,21046000.0,3349762000.0,3340540000.0,NaN

In [12]:
# income statement data for each ticker
income_statments = []
for ticker in ticker_list:
    tkr = yf.Ticker(ticker)
    income_statment = tkr.quarterly_financials.transpose()
    income_statment.insert(0, "Ticker", tkr.ticker)
    income_statments.append(income_statment.head(1))

final_is = pd.concat(income_statments, ignore_index=True)

display(final_is)

,Ticker,Tax Effect Of Unusual Items,Tax Rate For Calcs,Total Unusual Items,Total Unusual Items Excluding Goodwill,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Net Interest Income,Interest Expense,Interest Income,...,Rent Expense Supplemental,Earnings From Equity Interest Net Of Tax,Rent And Landing Fees,Provision For Doubtful Accounts,Other Taxes,Loss Adjustment Expense,Net Policyholder Benefits And Claims,Excise Taxes,Net Income Extraordinary,Securities Amortization
0,AX,0.0,0.289513,0.0,0.0,105206000.0,6847000.0,275464000.0,157258000.0,432722000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MRUS,13158000.0,0.258,51000000.0,51000000.0,-30923000.0,589000.0,8488000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TENX,0.0,0.0,NaN,NaN,-6267018.0,0.0,1027408.0,-465.0,1026943.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RYTM,0.0,0.002075,0.0,0.0,-43292000.0,383000.0,-1932000.0,5447000.0,3515000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GALT,0.0,0.0,2102000.0,2102000.0,-11967000.0,10000.0,-1641000.0,1725000.0,84000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,BBSI,684716.274229,0.271497,2522000.0,2522000.0,16800000.0,1938000.0,-45000.0,45000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,CWK,-2600000.0,0.4,-6500000.0,-6500000.0,1900000.0,48400000.0,-52300000.0,52300000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,CATO,0.0,0.4,NaN,NaN,-14052000.0,2711000.0,-5249000.0,NaN,-5190000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400,GPI,-2725500.0,0.237,-11500000.0,-11500000.0,127700000.0,29300000.0,-66700000.0,66700000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
401,NNI,6456211.924582,0.191426,33727000.0,33727000.0,63159000.0,26505000.0,80079000.0,141170000.0,221249000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# only include relevant columns
final_is = final_is[[
    'Ticker',                              
    'Total Revenue',
    'Gross Profit',  
    'Operating Income',
    'EBITDA',
    'Net Income',
    'Diluted EPS',
    'Diluted Average Shares',
    'Interest Expense',
]]
display (final_is)

,Ticker,Total Revenue,Gross Profit,Operating Income,EBITDA,Net Income,Diluted EPS,Diluted Average Shares,Interest Expense
0,AX,304660000.0,NaN,NaN,NaN,105206000.0,1.81,58174696.0,157258000.0
1,MRUS,9140000.0,NaN,-88652000.0,-88063000.0,-30923000.0,NaN,NaN,NaN
2,TENX,0.0,NaN,-7294772.0,-6267483.0,-6267018.0,NaN,NaN,-465.0
3,RYTM,41830000.0,38043000.0,-41255000.0,-37552000.0,-43292000.0,-0.72,61596442.0,5447000.0
4,GALT,0.0,NaN,-12428000.0,-10232000.0,-11967000.0,NaN,NaN,1725000.0
...,...,...,...,...,...,...,...,...,...
397,BBSI,304820000.0,71375000.0,20619000.0,25044000.0,16800000.0,0.63,26626000.0,45000.0
398,CWK,2284600000.0,384300000.0,51800000.0,105700000.0,1900000.0,0.01,232300000.0,52300000.0
399,CATO,157909000.0,46051000.0,-15281000.0,-743000.0,-14052000.0,NaN,NaN,NaN
400,GPI,5505300000.0,891900000.0,245300000.0,263500000.0,128100000.0,9.67,13100000.0,66700000.0
401,NNI,293017000.0,NaN,NaN,NaN,63159000.0,1.73,36461513.0,141170000.0

In [14]:
# cash flow data for each ticker
cash_flows = []
for ticker in ticker_list:
    tkr = yf.Ticker(ticker)
    cash_flow = tkr.quarterly_cash_flow.transpose()
    cash_flow.insert(0, "Ticker", tkr.ticker)
    cash_flows.append(cash_flow.head(1))

final_cf = pd.concat(cash_flows, ignore_index=True)

display(final_cf)

,Ticker,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Capital Expenditure,Interest Paid Supplemental Data,Income Tax Paid Supplemental Data,End Cash Position,Beginning Cash Position,...,Interest Paid Direct,Classesof Cash Payments,Paymentsto Suppliersfor Goodsand Services,Other Cash Paymentsfrom Operating Activities,Taxes Refund Paid Direct,Classesof Cash Receiptsfrom Operating Activities,Receiptsfrom Customers,Dividends Received Direct,Paymentson Behalfof Employees,Receiptsfrom Government Grants
0,AX,65130000.0,-25869000.0,0.0,18500000.0,-8551000.0,157056000.0,52309000.0,2257694000.0,2673431000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MRUS,-66678000.0,NaN,NaN,NaN,-20000.0,NaN,0.0,294031000.0,433772000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TENX,-3527033.0,NaN,-97.0,NaN,NaN,-465.0,NaN,94851000.0,98310918.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,RYTM,-18845000.0,NaN,NaN,NaN,NaN,NaN,NaN,89601000.0,47983000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GALT,-12791000.0,NaN,NaN,0.0,NaN,NaN,NaN,15120000.0,27060000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,BBSI,50216000.0,-7008000.0,0.0,0.0,-3159000.0,NaN,NaN,82588000.0,28715000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
388,CWK,-166600000.0,-10200000.0,-31400000.0,NaN,-4600000.0,NaN,NaN,640200000.0,814600000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
389,CATO,-7842000.0,-1479000.0,NaN,NaN,-1363000.0,NaN,NaN,23078000.0,23571000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390,GPI,106500000.0,-122800000.0,-3775400000.0,3822800000.0,-52200000.0,NaN,NaN,70500000.0,34400000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
391,NNI,197910000.0,-403000.0,-633744000.0,-54385000.0,NaN,140224000.0,1797000.0,931020000.0,899018000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
# only include relevant columns
final_cf = final_cf[['Ticker', 'Capital Expenditure',
                    'Free Cash Flow']]
display(final_cf)

    Ticker Capital Expenditure Free Cash Flow
0       AX          -8551000.0     65130000.0
1     MRUS            -20000.0    -66678000.0
2     TENX                 NaN     -3527033.0
3     RYTM                 NaN    -18845000.0
4     GALT                 NaN    -12791000.0
..     ...                 ...            ...
387   BBSI          -3159000.0     50216000.0
388    CWK          -4600000.0   -166600000.0
389   CATO          -1363000.0     -7842000.0
390    GPI         -52200000.0    106500000.0
391    NNI                 NaN    197910000.0

[392 rows x 3 columns]

In [16]:
# merge the balance sheet and income statement dataframe
yf_df_1 = pd.merge(final_bs, final_is, how='inner', on='Ticker')
display(yf_df_1)

,Ticker,Share Issued,Total Assets,Net PPE,Inventory,Accounts Receivable,Cash And Cash Equivalents,Total Debt,Long Term Debt,Current Debt,...,Retained Earnings,Working Capital,Total Revenue,Gross Profit,Operating Income,EBITDA,Net Income,Diluted EPS,Diluted Average Shares,Interest Expense
0,AX,70813637.0,23981154000.0,NaN,NaN,300907000.0,2001321000.0,437427000.0,437427000.0,0.0,...,2507850000.0,NaN,304660000.0,NaN,NaN,NaN,105206000.0,1.81,58174696.0,157258000.0
1,MRUS,68828749.0,782693000.0,20024000.0,NaN,1261000.0,293294000.0,9912000.0,NaN,NaN,...,-968387000.0,481996000.0,9140000.0,NaN,-88652000.0,-88063000.0,-30923000.0,NaN,NaN,NaN
2,TENX,298281.0,96686000.0,NaN,NaN,NaN,94851000.0,NaN,NaN,NaN,...,-314855000.0,91993000.0,0.0,NaN,-7294772.0,-6267483.0,-6267018.0,NaN,NaN,-465.0
3,RYTM,62390654.0,392273000.0,4109000.0,18741000.0,18512000.0,89137000.0,3938000.0,NaN,NaN,...,-1155338000.0,258683000.0,41830000.0,38043000.0,-41255000.0,-37552000.0,-43292000.0,-0.72,61596442.0,5447000.0
4,GALT,62308075.0,17495000.0,0.0,NaN,NaN,15120000.0,106245000.0,85109000.0,21117000.0,...,-401572000.0,-18157000.0,0.0,NaN,-12428000.0,-10232000.0,-11967000.0,NaN,NaN,1725000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397,BBSI,25784000.0,745508000.0,77110000.0,NaN,234533000.0,55367000.0,21446000.0,NaN,NaN,...,199995000.0,116546000.0,304820000.0,71375000.0,20619000.0,25044000.0,16800000.0,0.63,26626000.0,45000.0
398,CWK,231281053.0,7407500000.0,405300000.0,NaN,1307200000.0,623200000.0,3273800000.0,2910500000.0,108500000.0,...,-984000000.0,401600000.0,2284600000.0,384300000.0,51800000.0,105700000.0,1900000.0,0.01,232300000.0,52300000.0
399,CATO,20537776.0,452361000.0,209196000.0,110739000.0,11428000.0,20279000.0,145896000.0,NaN,NaN,...,31935000.0,34947000.0,157909000.0,46051000.0,-15281000.0,-743000.0,-14052000.0,NaN,NaN,NaN
400,GPI,24964378.0,9887000000.0,3211600000.0,2558400000.0,316700000.0,70500000.0,5268200000.0,2661100000.0,2302300000.0,...,4243900000.0,4900000.0,5505300000.0,891900000.0,245300000.0,263500000.0,128100000.0,9.67,13100000.0,66700000.0
401,NNI,47599083.0,13777753000.0,95185000.0,NaN,159934000.0,194518000.0,8309797000.0,7366632000.0,943165000.0,...,3340540000.0,NaN,293017000.0,NaN,NaN,NaN,63159000.0,1.73,36461513.0,141170000.0

In [17]:
# merge yf_df_1 with the cash flow statement dataframe
fin_stmts = pd.merge(yf_df_1, final_cf, how = 'inner', on = 'Ticker')
display(fin_stmts)

,Ticker,Share Issued,Total Assets,Net PPE,Inventory,Accounts Receivable,Cash And Cash Equivalents,Total Debt,Long Term Debt,Current Debt,...,Total Revenue,Gross Profit,Operating Income,EBITDA,Net Income,Diluted EPS,Diluted Average Shares,Interest Expense,Capital Expenditure,Free Cash Flow
0,AX,70813637.0,23981154000.0,NaN,NaN,300907000.0,2001321000.0,437427000.0,437427000.0,0.0,...,304660000.0,NaN,NaN,NaN,105206000.0,1.81,58174696.0,157258000.0,-8551000.0,65130000.0
1,MRUS,68828749.0,782693000.0,20024000.0,NaN,1261000.0,293294000.0,9912000.0,NaN,NaN,...,9140000.0,NaN,-88652000.0,-88063000.0,-30923000.0,NaN,NaN,NaN,-20000.0,-66678000.0
2,TENX,298281.0,96686000.0,NaN,NaN,NaN,94851000.0,NaN,NaN,NaN,...,0.0,NaN,-7294772.0,-6267483.0,-6267018.0,NaN,NaN,-465.0,NaN,-3527033.0
3,RYTM,62390654.0,392273000.0,4109000.0,18741000.0,18512000.0,89137000.0,3938000.0,NaN,NaN,...,41830000.0,38043000.0,-41255000.0,-37552000.0,-43292000.0,-0.72,61596442.0,5447000.0,NaN,-18845000.0
4,GALT,62308075.0,17495000.0,0.0,NaN,NaN,15120000.0,106245000.0,85109000.0,21117000.0,...,0.0,NaN,-12428000.0,-10232000.0,-11967000.0,NaN,NaN,1725000.0,NaN,-12791000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,BBSI,25784000.0,745508000.0,77110000.0,NaN,234533000.0,55367000.0,21446000.0,NaN,NaN,...,304820000.0,71375000.0,20619000.0,25044000.0,16800000.0,0.63,26626000.0,45000.0,-3159000.0,50216000.0
386,CWK,231281053.0,7407500000.0,405300000.0,NaN,1307200000.0,623200000.0,3273800000.0,2910500000.0,108500000.0,...,2284600000.0,384300000.0,51800000.0,105700000.0,1900000.0,0.01,232300000.0,52300000.0,-4600000.0,-166600000.0
387,CATO,20537776.0,452361000.0,209196000.0,110739000.0,11428000.0,20279000.0,145896000.0,NaN,NaN,...,157909000.0,46051000.0,-15281000.0,-743000.0,-14052000.0,NaN,NaN,NaN,-1363000.0,-7842000.0
388,GPI,24964378.0,9887000000.0,3211600000.0,2558400000.0,316700000.0,70500000.0,5268200000.0,2661100000.0,2302300000.0,...,5505300000.0,891900000.0,245300000.0,263500000.0,128100000.0,9.67,13100000.0,66700000.0,-52200000.0,106500000.0
389,NNI,47599083.0,13777753000.0,95185000.0,NaN,159934000.0,194518000.0,8309797000.0,7366632000.0,943165000.0,...,293017000.0,NaN,NaN,NaN,63159000.0,1.73,36461513.0,141170000.0,NaN,197910000.0

In [18]:
# check for missing values
fin_stmts.isna().sum()

Ticker                         0
Share Issued                   7
Total Assets                   0
Net PPE                       24
Inventory                    185
Accounts Receivable           67
Cash And Cash Equivalents      3
Total Debt                    12
Long Term Debt               135
Current Debt                 174
Accounts Payable              39
Stockholders Equity            0
Retained Earnings              8
Working Capital               44
Total Revenue                  2
Gross Profit                  99
Operating Income              46
EBITDA                        46
Net Income                     2
Diluted EPS                  218
Diluted Average Shares       218
Interest Expense             110
Capital Expenditure           71
Free Cash Flow                 0
dtype: int64

In [19]:
# drop columns with over 100 of the observations missing
fin_stmts = fin_stmts.drop(columns = ['Inventory', 'Long Term Debt', 'Current Debt', 'Diluted EPS', 'Diluted Average Shares', 'Interest Expense'])
fin_stmts.isna().sum()

Ticker                        0
Share Issued                  7
Total Assets                  0
Net PPE                      24
Accounts Receivable          67
Cash And Cash Equivalents     3
Total Debt                   12
Accounts Payable             39
Stockholders Equity           0
Retained Earnings             8
Working Capital              44
Total Revenue                 2
Gross Profit                 99
Operating Income             46
EBITDA                       46
Net Income                    2
Capital Expenditure          71
Free Cash Flow                0
dtype: int64

In [21]:
# save fin_stmts as a .csv (fin_stmts.csv)
fin_stmts.to_csv('fin_stms.csv', encoding = 'utf-8')